### ISSUE TITLE
Duplicates appear when calling replaceAll

### ISSUE THREAD

**Issue by bjohnso5** [Wrdlbrnft/SortedListAdapter#6]
I'm attempting to use SortedListAdapter, and everything seems to be working great, except that occasionally when I call replaceAll with items that should satisfy `isSameModelAs == true`, a duplicate entry will appear for a moment before being removed. 

Is this intended, and is there a way to modify this behaviour? I am currently checking against a unique id field (a MAC address) in my implmentation of `isSameModelAs`

**Comment by bjohnso5** [comment]
I believe my issue was actually being caused by my use of `setHasStableIds(true)` on the adapter - removing it and my implementation of `getItemId` seems to have solved my issue completely.

Thanks for a great library!

**Comment by bjohnso5** [comment]
I may have been too hasty in my testing - I see the duplicate behaviour without setting stable Ids as well.

I also now see a lot of flashing views, likely due to fast removes + adds happening for items that should be evaluating to the same. I'm curious if I may have misunderstood the reference implementation of `isSameModelAs` and `isContentTheSameAs`. Or, perhaps I should be more conservative in my use of calls to `replaceAll`?

**Comment by bjohnso5** [comment]
My issue is resolved - instead of calling `replaceAll()`, I am instead now calling `removeAll()` and `add()` in the same transaction. This, combined with stable IDs, seems to ensure I don't have either duplicated entries or flashing UI elements.

**Comment by Wrdlbrnft** [comment]
Hi, sorry for the late response. Using `replaceAll()` should be all you need to do. `removeAll()` and `add()` may work similarly but doing it this way is by far not as efficient and it may break some specific functionality. Also stable IDs are not necessary to make this work. If you post the code of your `Adapter`, `Comparator` and your `ViewModel`s I can probably help you pinpoint why it doesn't work.

**Comment by bjohnso5** [comment]
I may take you up on that, as I've noticed the unfortunate side effect of what I ended up with seems to scroll the list back to the top since all of the items are being removed and re-added each time anything changes.

**Comment by bjohnso5** [comment]
My intuition is that I'm having issues because I'm using multiple ViewModel implementation classes to denote what state an item is... I think when they're identified as changing from one view model class to another in the bind is where I'm seeing duplicates.

**Comment by Wrdlbrnft** [comment]
Multiple `ViewModel`s by itself should not be a problem. As long as your `Comparator` and the `isSameModelAs()` method is well behaved you should not have to worry about duplicates or any visual glitches. From my experience in most cases the problem is in the `Comparator`. I assume you are using the `ComparatorBuilder` class I provide in this library? I made it specifically because implementing a `Comparator` when dealing with multiple `ViewModel`s can be quite tricky to get right. If you can share some specific code I can at least take a look.

**Comment by bjohnso5** [comment]
Here's a [gist](https://gist.github.com/bjohnso5/b4832f2633272104f6126a9b8d7c455c) with the comparator that I'm using. The code path through the actual comparison seems to be convoluted at first glance, but for now the only thing that is being invoked is a single comparison of a `double` value.

**Comment by Wrdlbrnft** [comment]
So there doesn't seem anything wrong in the gist you posted, but the issue might be in the methods `distanceComparison()`, `sortByName()` or `sortByBeaconAttributes()`. The important part is that you have to ensure that the `Comparator` returns 0 when two items are the same. 

For example code like this would lead to duplicate items appearing:

```
if(lhs.getValue() > rhs.getValue()) {
    return -1;
} else {
    return 1;
}
```

However this code would work correctly:

```
if(lhs.getValue() > rhs.getValue()) {
    return -1;
} else if(lhs.getValue() == rhs.getValue()) {
    return 0;
} else {
    return 1;
}
```

From your code I assume you are already doing this, but just to be safe: `Double` comparison follows different rules since it is a floating point number. You have to use something like `Double.compare()` (and possibly also `Integer.signum()`) to properly compare two `Double` values for a `Comparator`.

As long you are properly comparing the values in the methods I mentioned above the `Comparator` should be fine and the problem would likely be somewhere else.

By the way: I like that you are using Kotlin :)

**Comment by bjohnso5** [comment]
I'm wondering if it might just be my use-case that doesn't fit very well. The application is constantly scanning for Bluetooth LE devices, and retrieving information about them, before being fed to the adapter for display. 

Perhaps the high volume of `replaceAll` calls is the issue that is causing the duplicates to appear. I started logging the number of items I was calling `replaceAll` with versus what the `itemManager.getCount()` was reporting, and I saw it steadily increasing in the item manager. It did eventually start to reap some of the duplicates, but it never keeps up and gets back to 1:1.

Just to confirm: the `isSameModelAs` method is the one that should identify if a view model instance already exists in the item manager's collection, and the `isContentTheSameAs` method determines whether view updates are required?

**Comment by Wrdlbrnft** [comment]
Exactly. High frequency updates should be no problem at all. Also the amount of items should make no difference, the only thing you should notice is that if you are dealing with 50000 items+ each update call should take about 200 to 500 milliseconds until it starts executing on screen. If you are just dealing with thousands of items all updates should be handed of to the `RecyclerView` virtually immediately. The library takes care of the queueing and managing of all the consecutive updates and it should work without a problem.

**Comment by bjohnso5** [comment]
Unfortunately due to deadline pressure I can't afford to spend any more time on this at the moment. I very much appreciate your assistance, and I hope that I can loop back in the future to integrate SortedListAdapter properly into this application.

Cheers!
